export enum ClientEmitMessages {
  SEND_MESSAGE = 'SEND_MESSAGE',
  CREATE_CONVERSATION = 'CREATE_CONVERSATION',
}

export enum ServerEmitMessages {
  NEW_MESSAGE = 'NEW_MESSAGE',
  NEW_CONVERSATION = 'NEW_CONVERSATION',
}
