export enum ClientEmitMessages {
  SEND_MESSAGE = 'SEND_MESSAGE',
  CREATE_CONVERSATION = 'CREATE_CONVERSATION',
  JOIN_CONVERSATION = 'JOIN_CONVERSATION',
  OUT_CONVERSATION = 'OUT_CONVERSATION',
  UPDATE_MEMBER = 'UPDATE_MEMBER',
}

export enum ServerEmitMessages {
  NEW_MESSAGE = 'NEW_MESSAGE',
  NEW_CONVERSATION = 'NEW_CONVERSATION',
  JOIN_CONVERSATION = 'JOIN_CONVERSATION',
  OUT_CONVERSATION = 'OUT_CONVERSATION',
  UPDATE_MEMBER = 'UPDATE_MEMBER',
}
